from __future__ import annotations

import json
import os
import platform
from pathlib import Path
from typing import Any


def _try_import(name: str):
    try:
        module = __import__(name)
        return module
    except Exception:
        return None


torch = _try_import("torch")
psutil = _try_import("psutil")
yaml = _try_import("yaml")


def detect_hardware() -> dict[str, Any]:
    """Detect available hardware and return a serializable dict.

    Tries to detect CUDA, MPS (Apple), CPU cores, and memory. Works without
    optional deps (torch/psutil) and falls back gracefully.
    """
    info: dict[str, Any] = {}

    info["platform"] = platform.system()
    info["python_version"] = platform.python_version()

    # CPU
    info["cpu_count_logical"] = os.cpu_count()

    # System memory
    try:
        if psutil:
            vm = psutil.virtual_memory()
            info["system_memory_bytes"] = int(vm.total)
        else:
            info["system_memory_bytes"] = None
    except Exception:
        info["system_memory_bytes"] = None

    # Torch-backed devices
    info["torch_available"] = torch is not None
    info["cuda_available"] = False
    info["cuda_device_count"] = 0
    info["cuda_devices"] = []
    info["mps_available"] = False

    if torch:
        try:
            info["cuda_available"] = torch.cuda.is_available()
            info["cuda_device_count"] = torch.cuda.device_count()
            for i in range(info["cuda_device_count"]):
                try:
                    prop = torch.cuda.get_device_properties(i)
                    info["cuda_devices"].append(
                        {
                            "id": i,
                            "name": str(prop.name),
                            "total_memory_bytes": int(prop.total_memory),
                        }
                    )
                except Exception:
                    info["cuda_devices"].append({"id": i, "name": None, "total_memory_bytes": None})
        except Exception:
            info["cuda_available"] = False
            info["cuda_device_count"] = 0
            info["cuda_devices"] = []

        # MPS (Apple Metal) detection
        try:
            mps_backend = getattr(torch.backends, "mps", None)
            info["mps_available"] = bool(
                mps_backend and getattr(mps_backend, "is_available", lambda: False)()
            )
        except Exception:
            info["mps_available"] = False

    # Environment shorthand: small summary
    info["summary"] = {
        "has_cuda": info.get("cuda_available", False),
        "cuda_count": info.get("cuda_device_count", 0),
        "has_mps": info.get("mps_available", False),
        "cpu_count": info.get("cpu_count_logical"),
    }

    return info


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    """Write `data` to `path` as YAML if possible, else JSON as fallback."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if yaml:
        try:
            with open(path, "w", encoding="utf-8") as fh:
                yaml.safe_dump(data, fh, sort_keys=False)
            return
        except Exception:
            pass

    # Fallback to JSON with .yaml extension
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)


def write_env_file(path: Path, data: dict[str, Any], prefix: str = "HPC_ODA_") -> None:
    """Write selected keys to a shell-style env file (KEY=VALUE).

    Only writes primitive values; lists/dicts are JSON-encoded.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []

    def encode_value(v: Any) -> str:
        if v is None:
            return ""
        if isinstance(v, bool):
            return json.dumps(v)
        if isinstance(v, (str, int, float)):
            return str(v)
        return json.dumps(v, ensure_ascii=False)

    # Flatten some high-value keys
    summary = data.get("summary", {}) if isinstance(data.get("summary"), dict) else {}

    def pick_value(primary_key: str, summary_key: str | None = None) -> Any:
        if primary_key in data:
            return data.get(primary_key)
        if summary_key:
            return summary.get(summary_key)
        return None

    keys = [
        ("has_cuda", "HAS_CUDA", "has_cuda"),
        ("cuda_device_count", "CUDA_COUNT", "cuda_count"),
        ("has_mps", "HAS_MPS", "has_mps"),
        ("cpu_count_logical", "CPU_COUNT"),
    ]

    for entry in keys:
        if len(entry) == 3:
            k, short, summary_key = entry
        else:
            k, short = entry
            summary_key = None
        val = pick_value(k, summary_key)
        lines.append(f"{prefix}{short}={encode_value(val)}")

    # Additional: system memory
    lines.append(f"{prefix}SYSTEM_MEMORY_BYTES={encode_value(data.get('system_memory_bytes'))}")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Generated by hpc_oda_commons.utils.hardware\n")
        fh.write("# Load with: set -a && source /path/to/file && set +a\n")
        for line in lines:
            fh.write(line + "\n")


def read_env_file(path: Path, prefix: str = "HPC_ODA_") -> dict[str, Any]:
    """Read a simple KEY=VALUE env file and return a dict of decoded values.

    Does not execute the file; parses lines of the form KEY=VALUE and JSON-decodes
    values that look like JSON structures.
    """
    path = Path(path)
    data: dict[str, Any] = {}
    if not path.exists():
        return data
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if k.startswith(prefix):
                short = k[len(prefix) :]
            else:
                short = k
            # try to decode JSON-like values
            try:
                val = json.loads(v)
            except Exception:
                val = v
            data[short] = val
    return data


if __name__ == "__main__":
    # Simple CLI
    import argparse

    parser = argparse.ArgumentParser(description="Detect hardware and write YAML/env file.")
    parser.add_argument("--out-yaml", default=".hpc_oda_hardware.yaml", help="YAML output path")
    parser.add_argument("--out-env", default=".hpc_oda_hardware.env", help="env file output path")
    args = parser.parse_args()
    info = detect_hardware()
    write_yaml(Path(args.out_yaml), info)
    write_env_file(Path(args.out_env), info)
    print(f"Wrote {args.out_yaml} and {args.out_env}")
